config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get '/games' => 'games#index'
  get '/players' => 'players#index'
  get '/:id' => 'players#show'
end

app/models/player.rb
class Player < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end
  
  def show
    @player = Player.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<%= link_to "Pick your gSchooler!", players_path %>

<div id="columns" class="columns_5">
<figure>
  <img src="http://i.imgur.com/XkeiCoy.png">
  <figcaption>Ellie</figcaption>
  <a class="button" href="#">Pick Ellie</a>
</figure>

<figure>
  <img src="http://i.imgur.com/Gwqm5QX.png">
  <figcaption>Paul</figcaption>
  <a class="button" href="#">Pick Paul</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>



<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>

<figure>
  <img src="http://i.imgur.com/NKyH3rw.png">
  <figcaption>Jenny</figcaption>
  <a class="button" href="#">Pick Jenny</a>
</figure>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GschoolWho</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<div id="columns" class="columns_5">
    <% @players.each do |player| %>
    <figure>
    <img src="<%= player.url %>">
      <figcaption><h3><%= player.name %></h3></figcaption>
      <a class="button" href="<%= player.id %>">Pick <%= player.name %></a>
      </figure>
    <% end %>
    </div>

app/views/players/show.html.erb
You've chosen <%= @player.name %>!

<div id="columns" class="columns_2">
    <figure>
      <img src="<%= @player.url %>">
      </figure>
  <figure>
      <figcaption>
        <b>Name:</b> <%= @player.name %><br>
        <b>Shirt Color 1:</b> <%= @player.shirt_color_1 %><br>
        <b>Shirt Color 2:</b> <%= @player.shirt_color_2 %><br>
        <b>Shirt Color 4:</b> <%= @player.shirt_color_3 %><br>
        <b>Hair Color:</b> <%= @player.hair_color %><br>
        <b>Eye Color:</b> <%= @player.eye_color %><br>
        <b>Smiling with Teeth?:</b> <%= @player.showing_teeth %><br>
        <b>Wearing a Necklace?:</b> <%= @player.necklace %><br>
        <b>Wearing Earrings?:</b> <%= @player.earrings %><br>
        <b>Wearing Glasses?:</b> <%= @player.glasses %><br>
        <b>Shirt has Collar?:</b> <%= @player.collar %><br>
        <b>Male or Female?:</b> <%= @player.male %><br>
      </figcaption>
    </figure>
</div>

app/views/welcome/index.html.erb
Welcome to gSchool Who?!

<%= link_to "Start a New Game!", games_path %>